### ISSUE TITLE
Usersnap Feedback - Stage Test (NL): Clicked the edit button on this case and got a strange er[...]

### ISSUE THREAD

**Issue by jesicarson** [participedia/usersnaps#1574]
**Sender**: jesi.carson@gmail.com
**Comment**: Stage Test (NL): Clicked the edit button on this case and got a strange error instead of being taken to the edit form (will paste screenshot)
[Open #1255 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-net-9cb6d041/1255)

<a href='https://usersnappublic.s3.amazonaws.com/2022-01-12/17-58/36d89b3b-60f7-4062-80ea-9c0520554209.png'>![Usersnap Feedback - Stage Test (NL): Clicked the edit button on this case and got a strange er(...)](https://usersnappublic.s3.amazonaws.com/2022-01-12/17-58/ddc57fce-821b-4cdf-bfb6-722edc3fbebf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2022-01-12/17-58/36d89b3b-60f7-4062-80ea-9c0520554209.png'>Download original image</a>

**Browser**: Chrome 97 (Macintosh)
**Referer**: [https://ppedia-stage.herokuapp.com/method/5993](https://ppedia-stage.herokuapp.com/method/5993)
**Screen size**: 1920 x 1080 **Browser size**: 1440 x 796

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

--

A friendly reminder from Usersnap 👋

There’s a new widget in town. Make your bug reporting process sleeker and more advanced by changing to the new project template.

Learn more about how to transfer your project (and what new features you’ve been missing out on) in this [blog post](https://usersnap.com/blog/platform-new-widget/).

**Comment by jesicarson** [comment]
Screenshot
![Screen Shot 2022-01-12 at 8 59 06 AM](https://user-images.githubusercontent.com/13560530/149186340-b4eeafc2-cc50-4bed-90da-90f1eb9a43b8.png)

**Comment by jesicarson** [comment]
copied text:

TypeError: Cannot read property 'type' of undefined
    at Object.getTranslatedEntryPlaceholders (/app/api/helpers/handlebars-helpers.js:286:26)
    at Object.wrapper (/app/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at Object.eval [as main] (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:21:150)
    at main (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at Object.invokePartial (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:334:12)
    at Object.invokePartialWrapper [as invokePartial] (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:84:39)
    at Object.eval [as main] (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:8:31)
    at main (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at ExpressHandlebars._renderTemplate (/app/node_modules/express-handlebars/lib/express-handlebars.js:250:12)
    at ExpressHandlebars.<anonymous> (/app/node_modules/express-handlebars/lib/express-handlebars.js:173:21)

**Comment by jesicarson** [comment]
https://ppedia-stage.herokuapp.com/method/5993/edit
