### ISSUE TITLE
[USERSNAP] stage test: in preview mode, changing the language to french only shows the english text (not the text i had entered in the french section of the form)

### ISSUE THREAD

**Issue by paninee** [participedia/usersnaps#1707]
**Sender**: jesi.carson@gmail.com
**Taken at**: http://ppedia-stage.herokuapp.com/method/7344
**Fields**:
- Add a comment: stage test: in preview mode, changing the language to french only shows the english text (not the text i had entered in the french section of the form)

![SCREENSHOT](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/05e886bc-8e6d-40ee-bb72-df29e019f257-annotated_7e165198-5082-4559-ad14-f918cf04457f.png?etag=f75e9e59929d0f31efa53d2ab35f9f72)
*[Download original image](https://resources.usersnap.com/company/1ce6c70e-fe74-45cb-a2bd-989d09ede09b/datapoint_screenshot/05e886bc-8e6d-40ee-bb72-df29e019f257-annotated_7e165198-5082-4559-ad14-f918cf04457f.png?etag=f75e9e59929d0f31efa53d2ab35f9f72)*

**Browser**: Chrome 102 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1259x976
**[Open #1390 in Usersnap](https://app.usersnap.com/l/feedback/af23b64a-2c53-402b-9927-51af3a0265bc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jesicarson** [comment]
also, clicking "continue editing" while previewing in FR threw an error:

![Screen Shot 2022-06-22 at 11 46 54 AM](https://user-images.githubusercontent.com/13560530/175113563-ff8d621c-6c2b-4173-8a7f-0eede61ec01a.png)

TypeError: Cannot read properties of undefined (reading 'type')
    at Object.getTranslatedEntryPlaceholders (/app/api/helpers/handlebars-helpers.js:298:26)
    at Object.wrapper (/app/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
    at Object.eval [as main] (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:23:150)
    at main (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at Object.invokePartial (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:334:12)
    at Object.invokePartialWrapper [as invokePartial] (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:84:39)
    at Object.eval [as main] (eval at createFunctionContext (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:10:31)
    at main (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at ExpressHandlebars._renderTemplate (/app/node_modules/express-handlebars/dist/express-handlebars.js:324:16)
    at ExpressHandlebars.<anonymous> (/app/node_modules/express-handlebars/dist/express-handlebars.js:240:37)
    at step (/app/node_modules/express-handlebars/dist/express-handlebars.js:49:23)
    at Object.next (/app/node_modules/express-handlebars/dist/express-handlebars.js:30:53)

**Comment by jesicarson** [comment]
If changing the site language while in preview mode breaks the draft, then we shouldn't let users change the language. There would need to be a popup explaining this I guess? Any ideas? @paninee

**Comment by paninee** [comment]
https://www.loom.com/share/7e08ed28af2d4aec838b3e276211b11e
